### ISSUE TITLE
CosmosDB Custom Connector for Azure AI Studio

### ISSUE THREAD

**Issue by rmazurik** [microsoft/contoso-support-pf-demo#3]
Hi Azure Team,
Great demo. I am currently trying to recreate the latter half of the presentation where you all seamlessly transitioned to Azure AI Studio to perform more of the evaluation and batch run comparison of your prompts. However, I am unable to recreate the custom connector for CosmosDB needed to run the prompt_flow within Azure AI Studio. The Azure AI Studio Connector is working with Key Value Pairs, where the local connector also has the properties "configs" and "secrets" that are expected and used within the prompt code. Any advice is greatly appreciated.

![image](https://github.com/microsoft/contoso-support-pf-demo/assets/107079616/674deb24-51f0-4531-8eff-ec6e3bab49ad)

![image](https://github.com/microsoft/contoso-support-pf-demo/assets/107079616/0807b7a3-b14c-407a-899f-54c2ce0adce3)

![image](https://github.com/microsoft/contoso-support-pf-demo/assets/107079616/f605e0d7-8687-410f-8dc6-61af3cd821fc)

**Comment by cloga** [comment]
Hi @rmazurik ,

To use custom connection in Prompt flow in AI studio, you need add extra meta to custom keys:
- azureml.flow.connection_type: Custom
- azureml.flow.module: promptflow.connections

![image](https://github.com/microsoft/contoso-support-pf-demo/assets/1320343/1b6de0e0-e6ba-4f53-95cd-3c3ef8891c7c)

Teams is working on to improve this part of experience.

**Comment by rmazurik** [comment]
@cloga Thank you very much for this feedback, this got me unblocked. Looking forward to the advancements to the platform from the team.
